In [38]:
import numpy as np
import torch 
import torch.nn as nn

np.random.seed(777)
torch.manual_seed(777)

In [39]:
def softmax(input, i):
    return np.exp(input[i]) / (np.sum(np.exp(input)) + 1e-6)

In [46]:
def attention(input):
    n = input.shape[0]
    d = input.shape[1]

    W_k = np.random.rand(d, d)
    W_q = np.random.rand(d, d)
    W_v = np.random.rand(d, d)
    #print(input, n, d)
    #print(input.shape, W_k.shape)
    k = np.matmul(input, W_k)
    #print(k)
    q = np.matmul(input, W_q)
    v = np.matmul(input, W_v)
    
    A = np.zeros((n, n))
    trans = np.matmul(q, k.T)
    root_d = np.sqrt(d)
    for i in range(n):
        A[i] = [softmax(trans[i] / root_d, j) for j in range(n)]
    # print(A)
    res = np.matmul(A, v)
    return res
    

In [49]:
n = np.array([[3, 4], [10, 8]]).astype(np.float64)
attention(n)

array([[11.3205707 , 11.28590956],
       [11.32057071, 11.28590957]])

In [ ]:
k= np.array([[2, 3, 5], [7, 8, 9]])
k = k.T
k

In [ ]:
n = np.array([[3, 4], [7, 8]])
a = np.ra
np.dot(n, a)

In [1]:
import numpy as np

In [6]:
n = np.array([[3, 4], [7, 8]]).astype(np.float64)
a = np.random.rand(2, 2)
np.dot(n, a)

array([[2.91543123, 2.66336308],
       [5.85400708, 5.33958981]])

In [2]:
a = np.random.rand(2, 2)
a

array([[0.2975064 , 0.73061944],
       [0.83582873, 0.8410795 ]])

In [4]:
a.dtype

dtype('float64')